Make go-ncs compile on Mac OS
When building the package against the NCSDK V1 API locally on macOS I
encountered the following error:

./ncs.h:12:3: error: unknown type name 'uint'; did you mean 'int'?

This was due to missing header file which this commit includes